"""Derived outputs, rebuilt from the store on every run.

Deleting them costs nothing; deleting the store costs everything (ADR-0002).

**The output directory is chosen by the mode, not by a flag.** `public` and
`redacted` write to `site/`; `full` writes to `.dendro-local/`, which the archive
template gitignores and no deployment reads. A `full` build therefore cannot
reach `site/` even by mistake, and there is nothing left for `publish` to catch.
"""

from __future__ import annotations

import json
from pathlib import Path

from core import graph as graph_module
from core import store

MODE_PUBLIC = "public"
MODE_REDACTED = "redacted"
MODE_FULL = "full"

SITE_DIR = "site"
LOCAL_DIR = ".dendro-local"


def output_dir(root: Path | str, mode: str) -> Path:
    """`full` never resolves to a directory that gets published."""
    return Path(root) / (LOCAL_DIR if mode == MODE_FULL else SITE_DIR)


def emit(payload: dict, root: Path | str, mode: str) -> dict[str, Path]:
    """Write `graph.json` and `graph.js` from the same object.

    Both ship: the `.json` for programs and agents (FR-017), the `.js` for the
    page. A browser blocks `fetch()` from a `file://` page under CORS, so the
    page is handed its data as a script that assigns a global — which is what
    makes the site work from a pen drive with no network (FR-016).
    """
    directory = output_dir(root, mode)
    directory.mkdir(parents=True, exist_ok=True)

    text = json.dumps(payload, indent=2, sort_keys=True, ensure_ascii=False) + "\n"
    json_path = directory / "graph.json"
    json_path.write_text(text, encoding="utf-8")

    js_path = directory / "graph.js"
    js_path.write_text(
        "// Generated by dendrograph. Assigned as a global because a browser\n"
        "// blocks fetch() from a file:// page; see contracts/graph.md.\n"
        f"window.DENDROGRAPH_GRAPH = {text.rstrip()};\n",
        encoding="utf-8",
    )
    written = {"graph.json": json_path, "graph.js": js_path}

    # As views vão junto: um site que precisa que alguém copie três arquivos à
    # mão não é "autocontido e sem configuração" (FR-016).
    views = Path(__file__).resolve().parent.parent / "views"
    for asset in ("loader.js", "style.css", "timeline.html", "graph.html"):
        source = views / asset
        if source.exists():
            destination = directory / asset
            destination.write_text(source.read_text(encoding="utf-8"), encoding="utf-8")
            written[asset] = destination
    return written


def build(root: Path | str = ".", *, mode: str = MODE_PUBLIC, config=None,
          unreachable: list | None = None, generated_at: str | None = None) -> dict:
    """Rebuild the derived outputs. Never touches the store."""
    artifacts = store.load_all(root)
    payload = graph_module.build(
        artifacts,
        config=config,
        build_mode=mode,
        unreachable=unreachable,
        generated_at=generated_at,
    )
    emit(payload, root, mode)
    return payload
