"""Derived outputs, rebuilt from the store on every run.

Deleting them costs nothing; deleting the store costs everything (ADR-0002).

**The output directory is chosen by the mode, not by a flag.** `public` and
`redacted` write to `site/`; `full` writes to `.dendro-local/`, which the archive
template gitignores and no deployment reads. A `full` build therefore cannot
reach `site/` even by mistake, and there is nothing left for `publish` to catch.
"""

from __future__ import annotations

import json
from pathlib import Path

from core import graph as graph_module
from core import llms as llms_module
from core import privacy
from core import sqlite as sqlite_module
from core import store

MODE_PUBLIC = "public"
MODE_REDACTED = "redacted"
MODE_FULL = "full"

SITE_DIR = "site"
LOCAL_DIR = ".dendro-local"


def output_dir(root: Path | str, mode: str) -> Path:
    """`full` never resolves to a directory that gets published."""
    return Path(root) / (LOCAL_DIR if mode == MODE_FULL else SITE_DIR)


def emit(payload: dict, root: Path | str, mode: str) -> dict[str, Path]:
    """Write `graph.json` and `graph.js` from the same object.

    Both ship: the `.json` for programs and agents (FR-017), the `.js` for the
    page. A browser blocks `fetch()` from a `file://` page under CORS, so the
    page is handed its data as a script that assigns a global — which is what
    makes the site work from a pen drive with no network (FR-016).
    """
    directory = output_dir(root, mode)
    directory.mkdir(parents=True, exist_ok=True)

    text = json.dumps(payload, indent=2, sort_keys=True, ensure_ascii=False) + "\n"
    json_path = directory / "graph.json"
    json_path.write_text(text, encoding="utf-8")

    js_path = directory / "graph.js"
    js_path.write_text(
        "// Generated by dendrograph. Assigned as a global because a browser\n"
        "// blocks fetch() from a file:// page; see contracts/graph.md.\n"
        f"window.DENDROGRAPH_GRAPH = {text.rstrip()};\n",
        encoding="utf-8",
    )
    written = {"graph.json": json_path, "graph.js": js_path}

    # Mesmo payload, três formas: JSON para programas, sqlite para quem
    # prefere consultar, prosa para um agente que não vai parsear nada.
    written[sqlite_module.FILENAME] = sqlite_module.write(payload, directory)
    written[llms_module.FILENAME] = llms_module.write(payload, directory)

    # As views vão junto: um site que precisa que alguém copie três arquivos à
    # mão não é "autocontido e sem configuração" (FR-016). As fontes viajam
    # junto pelo mesmo motivo: empacotar a IBM Plex é o que protege o design
    # de depender de uma CDN (ADR-0004).
    views = Path(__file__).resolve().parent.parent / "views"
    assets = list(views.glob("*.html")) + list(views.glob("*.js")) + list(views.glob("*.css"))
    fonts_dir = views / "fonts"
    if fonts_dir.exists():
        assets.extend(fonts_dir.glob("*.woff2"))
        # A licença viaja com a fonte porque a OFL exige isso de quem
        # redistribui, e cada site publicado é uma redistribuição.
        assets.extend(fonts_dir.glob("LICENSE*"))
    for source in assets:
        relative = source.relative_to(views)
        destination = directory / relative
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_bytes(source.read_bytes())
        written[str(relative)] = destination
    return written


def build(root: Path | str = ".", *, mode: str = MODE_PUBLIC, config=None,
          unreachable: list | None = None, generated_at: str | None = None,
          report=None) -> dict:
    """Rebuild the derived outputs. Never touches the store.

    Privacy is applied here, not in the store (ADR-0005): `select` decides who
    enters, and `redacted` mode carries only the withheld shape under
    `aggregates.private_withheld`. A *report* is filled with what was left out,
    so no build ever omits something silently.
    """
    artifacts = store.load_all(root)
    selection = privacy.select(artifacts, config=config, mode=mode)
    if report is not None:
        report.withheld = [
            f"{artifact.name or artifact.id} ({reason})"
            for artifact, reason in selection.withheld
        ]
    aggregates = (
        privacy.aggregate(selection.withheld) if mode == MODE_REDACTED else None
    )
    payload = graph_module.build(
        selection.included,
        config=config,
        build_mode=mode,
        aggregates=aggregates,
        unreachable=unreachable,
        generated_at=generated_at,
    )
    emit(payload, root, mode)
    return payload
